# Site settings
title:       Guy's Pod
email:
author:      Guy Podjarny
description: "Thoughts and research on Web Performance & Security"
baseurl:     ""
url:         "http://www.guypo.com/"

# Google analytics
google_analytics: UA-32373758-1

# Optional features
animated:           false
show_related_posts: false
show_post_footers:  false
inline-css: true

# Disqus post comments
# (leave blank to disable Disqus)
disqus_shortname: guypod

# Social icons
show_social_icons: true
github_username: guypod
stackoverflow_id:
twitter_username: guypod
google_plus_id:
linkedin_username: guypo
angellist_username: guypod
bitcoin_url:
paypal_url:
flattr_button:

# Post sharing icons
show_sharing_icons: false
share_text: 'Share this post!'
# Change to 'true' to enable individual icons
share_facebook: false
share_twitter: false
share_googleplus: false
share_linkedin: false
share_digg: false
share_tumblr: false
share_reddit: false
share_stumbleupon: false
share_hackernews: false

# Build settings
markdown:     redcarpet
redcarpet:
  extensions: ['smart', 'tables', 'with_toc_data']
permalink:    /:title
paginate:     8

sass:
  style: compressed

gems:
  - jekyll-redirect-from
